version: '2.4'

services:
  db:
    image: postgres
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - spotify_tagging_docker_network
  mailcatcher:
    image: dockage/mailcatcher:0.7.1
    ports:
      - "1080"
      - "1025"
  redis:
    image: 'bitnami/redis:4.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - spotify_tagging_docker_network
  web:
    build:
      context: .
      dockerfile: docker/local/Dockerfile-local
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailcatcher
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: spotify_tagging.settings
    networks:
      - spotify_tagging_docker_network
networks:
  spotify_tagging_docker_network:
    external: false
volumes:
  redis_data:
    driver: local
